# Variable 'artifactName' was defined in the Variables tab - This is from my fix branch
# Agent Queue 'Azure Pipelines' was used with unrecognized Agent Specification, vmImage property must be specified to determine image - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
variables:
- name: BuildParameters.solution1
  value: Boxfusion.SheshaFunctionalTests.sln
- name: BuildParameters.solution2
  value: ShaCompanyName.ShaProjectName.sln
- name: BuildParameters.configuration
  value: release
- name: pack-version
  value: ""
- name: isMain
  value: $[eq(variables['Build.SourceBranch'], 'f/dsd-npo')]

pr:
  branches:
    include:
    - dsd-npo
    exclude:
    - main
trigger:
  branches:
    include:
    - dsd-npo
    exclude:
    - main
    
pool: 
  name: Azure Pipelines
  vmImage1: windows-latest
  vmImage2: ubuntu-latest

# name: 2.0.0.$(BuildID)
stages:
- stage: build
  jobs:
  - job: Job_1
    displayName: Build_Functional_Shesha_API
    dependsOn: Job_2    
    pool:
      name: Azure Pipelines
      vmImage: windows-latest
    steps:
    - checkout: self
    - task: PowerShell@2
      displayName: Check if Pull Request
      retryCountOnTaskFailure: 5
      inputs:
        targetType: 'inline'
        script: |
          $targetBranch = ""
          if ("$(Build.SourceBranch)" -like "*/pull/*")
          {
              $targetBranch = "$(System.PullRequest.TargetBranch)"
              write-host "This is a Pull Request and the target branch is: $targetBranch"  
              write-host "##vso[task.setvariable variable=prTargetBranch]$targetBranch"
          }
          else
          {
            write-host "This is not a Pull Request and the target branch is set to empty string"  
            write-host "##vso[task.setvariable variable=prTargetBranch]''"                              
          }                         
        workingDirectory: '$(System.DefaultWorkingDirectory)'    
    - task: PowerShell@2
      displayName: Check to establish if this pipeline was triggered from a tag
      inputs:
        filePath: 'ReleaseFlow.ps1'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        arguments: '-PipeBuildNumber "$(Build.BuildNumber)" -PipeSourceBranch "$(Build.SourceBranch)" -PipeSourceVersion "$(Build.SourceVersion)" -PipeTargetBranch "$(prTargetBranch)" -PipeBuildId "$(Build.BuildId)"' 
    - task: PowerShell@2
      displayName: Output to console the current branch and version
      inputs:
        targetType: 'inline'
        script: |
          write-host "The current branch is: $(currentBranch)"
          write-host "The current version is: $(versionNo)"
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: PowerShell@2
      displayName: Create a txt file to carry the original branch name to the release pipeline  
      inputs:
        targetType: 'inline'
        script: |
          $variable = '$(currentBranch)'
          $variable | Out-File $(Build.ArtifactStagingDirectory)\branchName.txt
          Get-Content $(Build.ArtifactStagingDirectory)\branchName.txt
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: api-info-1'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'api-info-1'
    - task: UseDotNet@2
      displayName: Use .NET Core sdk 8.x
      inputs:
        version: 8.x
    - task: Assembly-Info-NetCore@3
      displayName: 'Set Assembly Manifest Data'
      inputs:
        InsertAttributes: true
        VersionNumber: "$(versionNo)"
        FileVersionNumber: "$(versionNo)"
        InformationalVersion: "$(versionNo)"
        PackageVersion: "$(versionNo)"
      # condition: ne(variables['currentBranch'], 'f/dsd-npo')
    - task: DotNetCoreCLI@2
      displayName: dotnet Restore
      inputs:
        command: 'restore'
        projects: shesha-core/src/**/*.csproj        
        feedsToUse: 'select'
        vstsFeed: '44b4667a-8963-403d-9962-bde66225adbd'
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        projects: shesha-core/Shesha.sln
        arguments: --configuration $(BuildParameters.configuration) -p:DefineConstants=DisableEditModule
    - task: DotNetCoreCLI@2
      displayName: dotnet publish
      inputs:
        command: publish
        publishWebProjects: false
        projects: shesha-core/Shesha.sln
        arguments: --configuration $(BuildParameters.configuration) --output $(build.artifactstagingdirectory) --no-build
        zipAfterPublish: false
        modifyOutputPath: false
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: shesha-core-api'
      inputs:
        ArtifactName: shesha-core-api
    - task: DotNetCoreCLI@2
      displayName: dotnet pack
      inputs:
        command: 'pack'
        packagesToPack: 'shesha-core/src/**/*.csproj'
        # packagesToPack: 'shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Web.Host.csproj'        
        configuration: '$(BuildParameters.configuration)'
        nobuild: false
        includesymbols: true
        includesource: true
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'versionNo'
    - task: PowerShell@2
      displayName: 'List Contents After Pack'
      inputs:
        targetType: 'inline'
        script: |
          # Clear Artifacts Directory
          ls
        workingDirectory: $(build.artifactstagingdirectory)/temp
      condition: eq(variables['currentBranch'], 'f/dsd-npo')
    - task: NuGetCommand@2
      displayName: dotnet push package
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/temp/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/temp/**/*.symbols.nupkg'
        # packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: '89b3d60a-0f8d-4f9c-9231-d8ec31f33661'
        publishPackageMetadata: true
        includeSymbols: true
        allowPackageConflicts: true
      condition: eq(variables['currentBranch'], 'f/dsd-npo')
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Nuget packs'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'packs-shesha-core'
  - job: Job_2
    displayName: SonarSource
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      fetchDepth: 0    
    - task: PowerShell@2
      displayName: Check if Pull Request
      retryCountOnTaskFailure: 5
      inputs:
        targetType: 'inline'
        script: |
          $targetBranch = ""
          if ("$(Build.SourceBranch)" -like "*/pull/*")
          {
              $targetBranch = "$(System.PullRequest.TargetBranch)"
              write-host "This is a Pull Request and the target branch is: $targetBranch"  
              write-host "##vso[task.setvariable variable=prTargetBranch]$targetBranch"
          }
          else
          {
            write-host "This is not a Pull Request and the target branch is set to empty string"  
            write-host "##vso[task.setvariable variable=prTargetBranch]''"                              
          }                         
        workingDirectory: '$(System.DefaultWorkingDirectory)'    
    - task: PowerShell@2
      displayName: Check to establish if this pipeline was triggered from a tag
      inputs:
        filePath: 'ReleaseFlow.ps1'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        arguments: '-PipeBuildNumber "$(Build.BuildNumber)" -PipeSourceBranch "$(Build.SourceBranch)" -PipeSourceVersion "$(Build.SourceVersion)" -PipeTargetBranch "$(prTargetBranch)" -PipeBuildId "$(Build.BuildId)"' 
    - task: PowerShell@2
      displayName: Output to console the current branch and version
      inputs:
        targetType: 'inline'
        script: |
          write-host "The current branch is: $(currentBranch)"
          write-host "The current version is: $(versionNo)"
        workingDirectory: '$(System.DefaultWorkingDirectory)'    
    - task: SonarCloudPrepare@1
      condition: eq(variables['System.PullRequest.IsFork'], 'false')
      inputs:
        SonarCloud: 'Sonarcloud' # This is the name of the service connection you created
        organization: 'boxfusion'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'Boxfusion_Shesha-Web-v3.0'
        cliProjectName: 'Shesha Web v3.0'
        cliProjectVersion: '$(versionNo)'
        cliSources: '$(System.DefaultWorkingDirectory)' # This is the relative path to your source code
    - task: SonarCloudAnalyze@1
      condition: eq(variables['System.PullRequest.IsFork'], 'false')    
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'
    - task: SonarQubePublish@5
      condition: eq(variables['System.PullRequest.IsFork'], 'false')
      inputs:
        pollingTimeoutSec: '300'
